### ISSUE TITLE
The photo-holder gets cut from top when window height is too small compared to width

### ISSUE THREAD

**Issue by gaurang847** [masquerade817/masquerade817.github.io#1]
![gaurang_page_smaller_height_window_issue_15](https://user-images.githubusercontent.com/12295171/87860263-aa9e6100-c959-11ea-9359-c97bb298b84b.gif)

**Comment by gaurang847** [comment]
```css
body > div{
    position: absolute;
    top:50%;
    transform: translateY(-50%);
}
```
<img src="https://user-images.githubusercontent.com/12295171/88453675-cbe5dc80-ce86-11ea-809e-257ea3aa9d1f.png" width=400px alt="screenshot explaning how top and transform work together to vertically align div"/>
